/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://6tsqpwsvm5apphe6a77nntdmxe.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mvc7ptd4ezchdgpir6fakzyspq",
    "aws_cloud_logic_custom": [
        {
            "name": "restapinotification",
            "endpoint": "https://j5e5tc1rfh.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:efd62309-39ab-467a-ae49-64dafa03c1bb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_7pkzg3CbJ",
    "aws_user_pools_web_client_id": "53k16cp6qrog2puouf30q8iouh",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "nursd-storage-49aaec2c110136-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
